Rework GP fake server to have a persistent configuration
Until now, all of our Flask-based servers for testing protocol
authentication flows have "cheated" a bit.

They're configurable (e.g.  should the authentication require a 2FA token,
or should it not?), but this configuration has not actually been persisted
by the server.

Instead, the server sends the client a session cookie which has the desired
*server* configuration glommed into it, and relies on the client sending
this cookie back on every request (which OpenConnect obliges, for
authentication requests) so that the server can "remember" what it's
configured to do.

This is very confusing to read and understand, and it's also untenable to
continue using it for fake servers that simulate external authentication
(SAML/SSO).  That's because external authentication uses a separate
browser/handler for the authentication flow, so it won't share the session
cookies.

This modifies the fake GP server to store a persistent in-memory
configuration which can easily be set and inspected with cURL:

    $ ./fake-gp-server localhost 8080 certs/server-{cert,key}.pem 2>&1 >/dev/null &
    $ curl -sk https://localhost:8080/CONFIGURE -d gw_2fa=1
    $ curl -sk https://localhost:8080/CONFIGURE
    Current configuration of fake GP server configuration:
    TestConfiguration(gateways=('Default gateway',), portal_2fa=False, gw_2fa=True, portal_cookie=None, portal_saml=None, gateway_saml=None)
    $ openconnect --protocol=gp localhost:8080
    Please login to this fake GP VPN portal
    Username: fakeusername
    Password: *******
    ...
    2FA challenge from gateway
    Challenge:

Contrast this with the old approach:

    $ ./fake-gp-server localhost 8080 certs/server-{cert,kem}.pem 2>&1 >/dev/null &
    $ openconnect --protocol=gp localhost:8080/global-protect/testconfig.esp?gw_2fa=1

The gp-auth-and-config tests are modified accordingly to set the persistent
configuration of the fake server.

Signed-off-by: Daniel Lenski <dlenski@gmail.com>

diff --git a/tests/gp-auth-and-config b/tests/gp-auth-and-config
--- a/tests/gp-auth-and-config
+++ b/tests/gp-auth-and-config
@@ -41,49 +41,67 @@ echo -n "Authenticating with username/password via portal... "
 
 echo ok
 
-echo -n "Authenticating with username/password, and selecting gateway, via portal... "
-( echo "test" | LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT --protocol=gp -q "$ADDRESS:443/global-protect/testconfig.esp?gateways=foo,bar,baz" --authgroup=bar -u test $FINGERPRINT --cookieonly >/dev/null 2>&1) ||
-    fail $PID "Could not receive cookie from fake GlobalProtect server"
-
-echo ok
-
 echo -n "Authenticating with username/password via gateway... "
 ( echo "test" | LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT --protocol=gp -q $ADDRESS:443/gateway -u test $FINGERPRINT --cookieonly >/dev/null 2>&1) ||
     fail $PID "Could not receive cookie from fake GlobalProtect server"
 
 echo ok
 
-echo -n "Authenticating with username/password/token via portal, then using portal-userauthcookie to continue through gateway... "
-( echo "test" | LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT --protocol=gp -q "$ADDRESS:443/global-protect/testconfig.esp?portal_2fa=1&gw_2fa=1&portal_cookie=portal-userauthcookie" -u test --token-mode=totp --token-secret=FAKE $FINGERPRINT --cookieonly >/dev/null 2>&1) ||
+echo "Configuring fake server to present a choice of 3 gateways in the portal."
+LD_PRELOAD=libsocket_wrapper.so curl -sk "https://$ADDRESS:443/CONFIGURE" -d gateways=foo,bar,baz
+
+echo -n "Authenticating with username/password, and selecting gateway, via portal... "
+( echo "test" | LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT --protocol=gp -q $ADDRESS:443/portal --authgroup=bar -u test $FINGERPRINT --cookieonly >/dev/null 2>&1) ||
     fail $PID "Could not receive cookie from fake GlobalProtect server"
 
 echo ok
 
-echo -n "Simulating completed SAML to portal, then using portal-userauthcookie to continue through SAML-requiring gateway... "
-( echo "prelogin-cookie" | LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT --protocol=gp -q "$ADDRESS:443/global-protect/testconfig.esp?portal_cookie=portal-userauthcookie&portal_saml=prelogin-cookie&gateway_saml=prelogin-cookie:prelogin-cookie" -u test $FINGERPRINT --cookieonly >/dev/null 2>&1) ||
+echo "Configuring fake server to require 2FA-token and to propagate portal authentication to gateway."
+LD_PRELOAD=libsocket_wrapper.so curl -sk "https://$ADDRESS:443/CONFIGURE" -d portal_2fa=1 -d gw_2fa=1 -d portal_cookie=portal-userauthcookie
+
+echo -n "Authenticating with username/password/2FA-token via portal, then continuing through 2FA-requiring gateway... "
+( echo "test" | LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT --protocol=gp -q $ADDRESS:443/portal -u test --token-mode=totp --token-secret=FAKE $FINGERPRINT --cookieonly >/dev/null 2>&1) ||
+    fail $PID "Could not receive cookie from fake GlobalProtect server"
+
+echo ok
+
+echo "Configuring fake server to require SAML for portal and gateway authentication, and to propagate portal authentication to gateway."
+LD_PRELOAD=libsocket_wrapper.so curl -sk "https://$ADDRESS:443/CONFIGURE" -d portal_cookie=portal-userauthcookie -d portal_saml=prelogin-cookie -d gateway_saml=prelogin-cookie
+
+echo -n "Simulating completed SAML to portal, then continuing through SAML-requiring gateway... "
+( echo "prelogin-cookie" | LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT --protocol=gp -q $ADDRESS:443/portal:prelogin-cookie -u test $FINGERPRINT --cookieonly >/dev/null 2>&1) ||
 test $? = 2 || # what OpenConnect returns when server rejects cookie upon tunnel connection, as the fake server does
     fail $PID "Something went wrong in fake GlobalProtect server (other than the expected rejection of cookie)"
 
 echo ok
+
+echo "Configuring fake server to require SAML for gateway authentication only."
+LD_PRELOAD=libsocket_wrapper.so curl -sk "https://$ADDRESS:443/CONFIGURE" -d gateway_saml=prelogin-cookie
 
 echo -n "Simulating completed SAML to gateway... "
-( echo "prelogin-cookie" | LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT --protocol=gp -q "$ADDRESS:443/ssl-vpn/testconfig.esp?gateway_saml=prelogin-cookie:prelogin-cookie" -u test $FINGERPRINT --cookieonly >/dev/null 2>&1) ||
+( echo "prelogin-cookie" | LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT --protocol=gp -q $ADDRESS:443/gateway:prelogin-cookie -u test $FINGERPRINT --cookieonly >/dev/null 2>&1) ||
 test $? = 2 || # what OpenConnect returns when server rejects cookie upon tunnel connection, as the fake server does
     fail $PID "Something went wrong in fake GlobalProtect server (other than the expected rejection of cookie)"
 
 echo ok
 
+echo "Configuring fake server to require 2FA-token for gateway authentication."
+LD_PRELOAD=libsocket_wrapper.so curl -sk "https://$ADDRESS:443/CONFIGURE" -d gw_2fa=1
+
 echo -n "Authenticating with username/password via portal, then +token via gateway... "
-( echo "test" | LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT --protocol=gp -q "$ADDRESS:443/global-protect/testconfig.esp?gw_2fa=1" -u test --token-mode=totp --token-secret=FAKE $FINGERPRINT --cookieonly >/dev/null 2>&1) ||
+( echo "test" | LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT --protocol=gp -q $ADDRESS:443/portal -u test --token-mode=totp --token-secret=FAKE $FINGERPRINT --cookieonly >/dev/null 2>&1) ||
     fail $PID "Could not receive cookie from fake GlobalProtect server"
 
 echo ok
 
 echo -n "Authenticating with username/password/token via gateway... "
-( echo "test" | LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT --protocol=gp -q "$ADDRESS:443/ssl-vpn/testconfig.esp?gw_2fa=1" -u test --token-mode=totp --token-secret=FAKE $FINGERPRINT --cookieonly >/dev/null 2>&1) ||
+( echo "test" | LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT --protocol=gp -q $ADDRESS:443/gateway -u test --token-mode=totp --token-secret=FAKE $FINGERPRINT --cookieonly >/dev/null 2>&1) ||
     fail $PID "Could not receive cookie from fake GlobalProtect server"
 
 echo ok
+
+echo "Resetting fake server to default configuration."
+LD_PRELOAD=libsocket_wrapper.so curl -sk -X POST "https://$ADDRESS:443/CONFIGURE"
 
 echo -n "Authenticating with username/password via portal, then proceeding to tunnel stage... "
 echo "test" | LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT --protocol=gp -q $ADDRESS:443/portal -u test $FINGERPRINT >/dev/null 2>&1
